Remove files that no longer exist.
This was breaking building of the gem with the following error:

```
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["vendor/assets/javascripts/message-bus-ajax.js", "vendor/assets/javascripts/message-bus.js"] are not files
```