Handle Client#add failure on PostgreSQL
Client#hold can silently swallow errors and return nil for
PG::ConnectionBad and PG::UnableToSend exceptions.  If that
happens during #add, don't try to check whether to clear the
backlog, which would raise a NoMethodError.

Should work around the following CI failure:

```
NoMethodError: undefined method `%' for nil:NilClass
    /home/runner/work/message_bus/message_bus/lib/message_bus/backends/postgres.rb:280:in `publish'
    spec/lib/message_bus/backend_spec.rb:131:in `block (2 levels) in <top (required)>'
```